// src/routes/index.jsx
export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  dashboardBuyer: "/dashboard-buyer",
  dashboardSeller: "/dashboard-seller",
  dashboardAdmin: "/dashboard-admin",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  verifyEmail: "/verify-email",
  vehicles: "/vehicles",
  electrics: "/electrics",
  favorites: "/favorites",
  aboutUs: "/about",
  support: "/support",
  postVehicles: "/post/vehicles",
  postElectric: "/post/electrics",
  vehicleDetail: "/vehicles/:postID",
  electricDetail: "/electrics/:postID",
};
