spring.application.name=voltera

#JWT
jwt.secret=mySecretKey123
jwt.experation=86400000

#gmail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=buigiahuy1506@gmail.com
spring.mail.password=huybui123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Database configuration
spring.datasource.url=jdbc:postgresql://hopper.proxy.rlwy.net:34798/railway
spring.datasource.username=postgres
spring.datasource.password=XUXFPPdbEatTVTEHiFGfVGWozrGXilWc
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Config Oauth2
spring.security.oauth2.client.registration.google.client-id=816749037915-c1hnckj61jud3c1h1mt0nmi54h4nbq86.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile