spring.application.name=voltera

spring.datasource.url=jdbc:postgresql://hopper.proxy.rlwy.net:34798/railway
spring.datasource.username=postgres
spring.datasource.password=XUXFPPdbEatTVTEHiFGfVGWozrGXilWc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=o2aXuvh3lyMdy_cLqc3xvKB2jM6D905ulGeKtsnPEVk=
jwt.expiration=86400000

# AWS Credentials (dùng cho development, không dùng trong production)
aws.access-key=YOUR
aws.secret-key=YOUR
aws.region=us
aws.s3.bucket=voltera-ev-bucket

logging.level.software.amazon.awssdk=DEBUG
