spring.application.name=voltera

#JWT
jwt.secret=mySecretKey123
jwt.expiration=86400000

# AWS Credentials (dùng cho development, không dùng trong production)
aws.access-key=YOUR_ACCESS_KEY_ID  # Thay b?ng Access Key t? AWS IAM User
aws.secret-key=YOUR_SECRET_ACCESS_KEY  # Thay b?ng Secret Key
aws.region=us-east-1  # Region c?a bucket S3 (ví d?: us-east-1, ap-southeast-1)
aws.s3.bucket=voltera-ev-bucket
logging.level.software.amazon.awssdk=DEBUG