spring.application.name=voltera

spring.datasource.url=jdbc:postgresql://hopper.proxy.rlwy.net:34798/railway
spring.datasource.username=postgres
spring.datasource.password=XUXFPPdbEatTVTEHiFGfVGWozrGXilWc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=o2aXuvh3lyMdy_cLqc3xvKB2jM6D905ulGeKtsnPEVk=
jwt.expiration=86400000

# AWS Credentials (dùng cho development, không dùng trong production)
aws.s3.bucket-name=your-bucket-name
aws.s3.region=ap-southeast-1
aws.access-key-id=your-access-key
aws.secret-access-key=your-secret-key

logging.level.software.amazon.awssdk=DEBUG

# #Config oauth2
# spring.security.oauth2.client.registration.google.client-id=816749037915-c1hnckj61jud3c1h1mt0nmi54h4nbq86.apps.googleusercontent.com
# spring.security.oauth2.client.registration.google.client-secret=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
# spring.security.oauth2.client.registration.google.scope=email,profile

# spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
# spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
# spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
# spring.security.oauth2.client.provider.google.user-name-attribute=sub